### ISSUE TITLE
Branch name is missing 'n' letter at the end

### ISSUE THREAD

**Issue by berilunay** [aws-samples/amazon-bedrock-agents-cancer-biomarker-discovery#42]
```
GitBranch:
    Type: String
    Description: The github branch to clone 
    Default: main
    AllowedValues:
      - main
      - multi-agent-collaboratio
```
