### ISSUE TITLE
Upper case in stack name causes deployment failure

### ISSUE THREAD

**Issue by rstrahan** [aws-samples/amazon-bedrock-agents-cancer-biomarker-discovery#9]
The stack failed to deploy:

![image](https://github.com/user-attachments/assets/8a8f92e0-734c-46cd-ae9b-eaf3d61fd35c)

The reason is the explicit use of AWS::StackName in the BucketName.

```
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AWS::StackName}-${AWS::AccountId}-${AWS::Region}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
```

Valid Stack names include uppercase (eg `Agent-BioMarkerDiscovery`) but bucket names do not.  
I think the template should ideally avoid explicitly naming the bucket - it will be named automatically by CfN if you omit the `BucketName` property.
